/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq;


import com.forumdeitroll.persistence.jooq.tables.Ads;
import com.forumdeitroll.persistence.jooq.tables.Authors;
import com.forumdeitroll.persistence.jooq.tables.Bookmarks;
import com.forumdeitroll.persistence.jooq.tables.Digest;
import com.forumdeitroll.persistence.jooq.tables.DigestParticipant;
import com.forumdeitroll.persistence.jooq.tables.Likes;
import com.forumdeitroll.persistence.jooq.tables.Logins;
import com.forumdeitroll.persistence.jooq.tables.Messages;
import com.forumdeitroll.persistence.jooq.tables.Notification;
import com.forumdeitroll.persistence.jooq.tables.Preferences;
import com.forumdeitroll.persistence.jooq.tables.PvtContent;
import com.forumdeitroll.persistence.jooq.tables.PvtRecipient;
import com.forumdeitroll.persistence.jooq.tables.Quotes;
import com.forumdeitroll.persistence.jooq.tables.Sysinfo;
import com.forumdeitroll.persistence.jooq.tables.Tagnames;
import com.forumdeitroll.persistence.jooq.tables.Tags;
import com.forumdeitroll.persistence.jooq.tables.TagsBind;
import com.forumdeitroll.persistence.jooq.tables.Threads;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in fdtsucker
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table fdtsucker.ads
	 */
	public static final Ads ADS = com.forumdeitroll.persistence.jooq.tables.Ads.ADS;

	/**
	 * The table fdtsucker.authors
	 */
	public static final Authors AUTHORS = com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS;

	/**
	 * The table fdtsucker.bookmarks
	 */
	public static final Bookmarks BOOKMARKS = com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS;

	/**
	 * The table fdtsucker.digest
	 */
	public static final Digest DIGEST = com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST;

	/**
	 * The table fdtsucker.digest_participant
	 */
	public static final DigestParticipant DIGEST_PARTICIPANT = com.forumdeitroll.persistence.jooq.tables.DigestParticipant.DIGEST_PARTICIPANT;

	/**
	 * The table fdtsucker.likes
	 */
	public static final Likes LIKES = com.forumdeitroll.persistence.jooq.tables.Likes.LIKES;

	/**
	 * The table fdtsucker.logins
	 */
	public static final Logins LOGINS = com.forumdeitroll.persistence.jooq.tables.Logins.LOGINS;

	/**
	 * The table fdtsucker.messages
	 */
	public static final Messages MESSAGES = com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES;

	/**
	 * The table fdtsucker.notification
	 */
	public static final Notification NOTIFICATION = com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION;

	/**
	 * The table fdtsucker.preferences
	 */
	public static final Preferences PREFERENCES = com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES;

	/**
	 * The table fdtsucker.pvt_content
	 */
	public static final PvtContent PVT_CONTENT = com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT;

	/**
	 * The table fdtsucker.pvt_recipient
	 */
	public static final PvtRecipient PVT_RECIPIENT = com.forumdeitroll.persistence.jooq.tables.PvtRecipient.PVT_RECIPIENT;

	/**
	 * The table fdtsucker.quotes
	 */
	public static final Quotes QUOTES = com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES;

	/**
	 * The table fdtsucker.sysinfo
	 */
	public static final Sysinfo SYSINFO = com.forumdeitroll.persistence.jooq.tables.Sysinfo.SYSINFO;

	/**
	 * The table fdtsucker.tagnames
	 */
	public static final Tagnames TAGNAMES = com.forumdeitroll.persistence.jooq.tables.Tagnames.TAGNAMES;

	/**
	 * The table fdtsucker.tags
	 */
	public static final Tags TAGS = com.forumdeitroll.persistence.jooq.tables.Tags.TAGS;

	/**
	 * The table fdtsucker.tags_bind
	 */
	public static final TagsBind TAGS_BIND = com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND;

	/**
	 * The table fdtsucker.threads
	 */
	public static final Threads THREADS = com.forumdeitroll.persistence.jooq.tables.Threads.THREADS;
}
