/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ads extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> {

	private static final long serialVersionUID = 587871801;

	/**
	 * The singleton instance of <code>fdtsucker.ads</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Ads ADS = new com.forumdeitroll.persistence.jooq.tables.Ads();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.AdsRecord.class;
	}

	/**
	 * The column <code>fdtsucker.ads.id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.ads.title</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.ads.visurl</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.String> VISURL = createField("visurl", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.ads.content</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.ads</code> table reference
	 */
	public Ads() {
		this("ads", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.ads</code> table reference
	 */
	public Ads(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Ads.ADS);
	}

	private Ads(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ads(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.Integer> getIdentity() {
		return com.forumdeitroll.persistence.jooq.Keys.IDENTITY_ADS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_ADS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_ADS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Ads as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Ads(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Ads rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Ads(name, null);
	}
}
