/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authors extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord> {

	private static final long serialVersionUID = -1532896238;

	/**
	 * The singleton instance of <code>fdtsucker.authors</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Authors AUTHORS = new com.forumdeitroll.persistence.jooq.tables.Authors();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord.class;
	}

	/**
	 * The column <code>fdtsucker.authors.nick</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, java.lang.String> NICK = createField("nick", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.authors.messages</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, java.lang.Integer> MESSAGES = createField("messages", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.authors.avatar</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, byte[]> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.BLOB.length(16777215), this, "");

	/**
	 * The column <code>fdtsucker.authors.password</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.authors.salt</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, java.lang.String> SALT = createField("salt", org.jooq.impl.SQLDataType.CLOB.length(255), this, "");

	/**
	 * The column <code>fdtsucker.authors.hash</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, java.lang.String> HASH = createField("hash", org.jooq.impl.SQLDataType.CLOB.length(255), this, "");

	/**
	 * The column <code>fdtsucker.authors.signature_image</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord, byte[]> SIGNATURE_IMAGE = createField("signature_image", org.jooq.impl.SQLDataType.BLOB.length(16777215), this, "");

	/**
	 * Create a <code>fdtsucker.authors</code> table reference
	 */
	public Authors() {
		this("authors", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.authors</code> table reference
	 */
	public Authors(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS);
	}

	private Authors(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Authors(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Authors as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Authors(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Authors rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Authors(name, null);
	}
}
