/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmarks extends TableImpl<BookmarksRecord> {

	private static final long serialVersionUID = -713923974;

	/**
	 * The reference instance of <code>fdtsucker.bookmarks</code>
	 */
	public static final Bookmarks BOOKMARKS = new Bookmarks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BookmarksRecord> getRecordType() {
		return BookmarksRecord.class;
	}

	/**
	 * The column <code>fdtsucker.bookmarks.nick</code>.
	 */
	public final TableField<BookmarksRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.bookmarks.msgId</code>.
	 */
	public final TableField<BookmarksRecord, Integer> MSGID = createField("msgId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.bookmarks.subject</code>.
	 */
	public final TableField<BookmarksRecord, String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.bookmarks</code> table reference
	 */
	public Bookmarks() {
		this("bookmarks", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.bookmarks</code> table reference
	 */
	public Bookmarks(String alias) {
		this(alias, BOOKMARKS);
	}

	private Bookmarks(String alias, Table<BookmarksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bookmarks(String alias, Table<BookmarksRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Bookmarks as(String alias) {
		return new Bookmarks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Bookmarks rename(String name) {
		return new Bookmarks(name, null);
	}
}
