/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmarks extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord> {

	private static final long serialVersionUID = -2046920713;

	/**
	 * The singleton instance of <code>fdtsucker.bookmarks</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Bookmarks BOOKMARKS = new com.forumdeitroll.persistence.jooq.tables.Bookmarks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord.class;
	}

	/**
	 * The column <code>fdtsucker.bookmarks.nick</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord, java.lang.String> NICK = createField("nick", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.bookmarks.msgId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord, java.lang.Integer> MSGID = createField("msgId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.bookmarks.subject</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord, java.lang.String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.bookmarks</code> table reference
	 */
	public Bookmarks() {
		this("bookmarks", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.bookmarks</code> table reference
	 */
	public Bookmarks(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS);
	}

	private Bookmarks(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bookmarks(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Bookmarks as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Bookmarks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Bookmarks rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Bookmarks(name, null);
	}
}
