/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.LikesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Likes extends TableImpl<LikesRecord> {

	private static final long serialVersionUID = 125794556;

	/**
	 * The reference instance of <code>fdtsucker.likes</code>
	 */
	public static final Likes LIKES = new Likes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LikesRecord> getRecordType() {
		return LikesRecord.class;
	}

	/**
	 * The column <code>fdtsucker.likes.nick</code>.
	 */
	public final TableField<LikesRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.likes.msgId</code>.
	 */
	public final TableField<LikesRecord, Integer> MSGID = createField("msgId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.likes.vote</code>.
	 */
	public final TableField<LikesRecord, Byte> VOTE = createField("vote", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>fdtsucker.likes</code> table reference
	 */
	public Likes() {
		this("likes", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.likes</code> table reference
	 */
	public Likes(String alias) {
		this(alias, LIKES);
	}

	private Likes(String alias, Table<LikesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Likes(String alias, Table<LikesRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Likes as(String alias) {
		return new Likes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Likes rename(String name) {
		return new Likes(name, null);
	}
}
