/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.LoginsRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Logins extends TableImpl<LoginsRecord> {

	private static final long serialVersionUID = -851525870;

	/**
	 * The reference instance of <code>fdtsucker.logins</code>
	 */
	public static final Logins LOGINS = new Logins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LoginsRecord> getRecordType() {
		return LoginsRecord.class;
	}

	/**
	 * The column <code>fdtsucker.logins.nick</code>.
	 */
	public final TableField<LoginsRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.logins.loginKey</code>.
	 */
	public final TableField<LoginsRecord, String> LOGINKEY = createField("loginKey", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.logins.tstamp</code>.
	 */
	public final TableField<LoginsRecord, Timestamp> TSTAMP = createField("tstamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.logins</code> table reference
	 */
	public Logins() {
		this("logins", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.logins</code> table reference
	 */
	public Logins(String alias) {
		this(alias, LOGINS);
	}

	private Logins(String alias, Table<LoginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Logins(String alias, Table<LoginsRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Logins as(String alias) {
		return new Logins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Logins rename(String name) {
		return new Logins(name, null);
	}
}
