/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Messages extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> {

	private static final long serialVersionUID = -1410294224;

	/**
	 * The singleton instance of <code>fdtsucker.messages</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Messages MESSAGES = new com.forumdeitroll.persistence.jooq.tables.Messages();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord.class;
	}

	/**
	 * The column <code>fdtsucker.messages.id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.messages.text</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.messages.date</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.messages.subject</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.messages.threadId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> THREADID = createField("threadId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.messages.parentId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> PARENTID = createField("parentId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.messages.author</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>fdtsucker.messages.forum</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.String> FORUM = createField("forum", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>fdtsucker.messages.visible</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Byte> VISIBLE = createField("visible", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>fdtsucker.messages.rank</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>fdtsucker.messages</code> table reference
	 */
	public Messages() {
		this("messages", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.messages</code> table reference
	 */
	public Messages(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES);
	}

	private Messages(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Messages(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> getIdentity() {
		return com.forumdeitroll.persistence.jooq.Keys.IDENTITY_MESSAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_MESSAGES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_MESSAGES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Messages as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Messages(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Messages rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Messages(name, null);
	}
}
