/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notification extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> {

	private static final long serialVersionUID = -908845236;

	/**
	 * The singleton instance of <code>fdtsucker.notification</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Notification NOTIFICATION = new com.forumdeitroll.persistence.jooq.tables.Notification();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord.class;
	}

	/**
	 * The column <code>fdtsucker.notification.id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.notification.fromNick</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.String> FROMNICK = createField("fromNick", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.notification.toNick</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.String> TONICK = createField("toNick", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.notification.msgId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.Integer> MSGID = createField("msgId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.notification</code> table reference
	 */
	public Notification() {
		this("notification", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.notification</code> table reference
	 */
	public Notification(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION);
	}

	private Notification(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Notification(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.Integer> getIdentity() {
		return com.forumdeitroll.persistence.jooq.Keys.IDENTITY_NOTIFICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_NOTIFICATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_NOTIFICATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Notification as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Notification(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Notification rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Notification(name, null);
	}
}
