/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poll extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> {

	private static final long serialVersionUID = 1213129647;

	/**
	 * The singleton instance of <code>fdtsucker.poll</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Poll POLL = new com.forumdeitroll.persistence.jooq.tables.Poll();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.PollRecord.class;
	}

	/**
	 * The column <code>fdtsucker.poll.id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll.title</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll.text</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.CLOB.length(16777215).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll.author</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll.creationDate</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.sql.Timestamp> CREATIONDATE = createField("creationDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll.updateDate</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.sql.Timestamp> UPDATEDATE = createField("updateDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.poll</code> table reference
	 */
	public Poll() {
		this("poll", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.poll</code> table reference
	 */
	public Poll(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Poll.POLL);
	}

	private Poll(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> aliased) {
		this(alias, aliased, null);
	}

	private Poll(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.Integer> getIdentity() {
		return com.forumdeitroll.persistence.jooq.Keys.IDENTITY_POLL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_POLL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PollRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PollRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_POLL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Poll as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Poll(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Poll rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Poll(name, null);
	}
}
