/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollQuestion extends TableImpl<PollQuestionRecord> {

	private static final long serialVersionUID = 62884606;

	/**
	 * The reference instance of <code>fdtsucker.poll_question</code>
	 */
	public static final PollQuestion POLL_QUESTION = new PollQuestion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PollQuestionRecord> getRecordType() {
		return PollQuestionRecord.class;
	}

	/**
	 * The column <code>fdtsucker.poll_question.pollId</code>.
	 */
	public final TableField<PollQuestionRecord, Integer> POLLID = createField("pollId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_question.sequence</code>.
	 */
	public final TableField<PollQuestionRecord, Integer> SEQUENCE = createField("sequence", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_question.text</code>.
	 */
	public final TableField<PollQuestionRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_question.votes</code>.
	 */
	public final TableField<PollQuestionRecord, Integer> VOTES = createField("votes", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.poll_question</code> table reference
	 */
	public PollQuestion() {
		this("poll_question", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.poll_question</code> table reference
	 */
	public PollQuestion(String alias) {
		this(alias, POLL_QUESTION);
	}

	private PollQuestion(String alias, Table<PollQuestionRecord> aliased) {
		this(alias, aliased, null);
	}

	private PollQuestion(String alias, Table<PollQuestionRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollQuestion as(String alias) {
		return new PollQuestion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PollQuestion rename(String name) {
		return new PollQuestion(name, null);
	}
}
