/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollQuestion extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord> {

	private static final long serialVersionUID = -909549248;

	/**
	 * The singleton instance of <code>fdtsucker.poll_question</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PollQuestion POLL_QUESTION = new com.forumdeitroll.persistence.jooq.tables.PollQuestion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord.class;
	}

	/**
	 * The column <code>fdtsucker.poll_question.pollId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord, java.lang.Integer> POLLID = createField("pollId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_question.sequence</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord, java.lang.Integer> SEQUENCE = createField("sequence", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_question.text</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_question.votes</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord, java.lang.Integer> VOTES = createField("votes", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.poll_question</code> table reference
	 */
	public PollQuestion() {
		this("poll_question", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.poll_question</code> table reference
	 */
	public PollQuestion(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.PollQuestion.POLL_QUESTION);
	}

	private PollQuestion(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord> aliased) {
		this(alias, aliased, null);
	}

	private PollQuestion(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PollQuestionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.PollQuestion as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.PollQuestion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.PollQuestion rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.PollQuestion(name, null);
	}
}
