/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PvtContent extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> {

	private static final long serialVersionUID = -1731192213;

	/**
	 * The singleton instance of <code>fdtsucker.pvt_content</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PvtContent PVT_CONTENT = new com.forumdeitroll.persistence.jooq.tables.PvtContent();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord.class;
	}

	/**
	 * The column <code>fdtsucker.pvt_content.id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_content.sender</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.String> SENDER = createField("sender", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_content.content</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.length(16777215).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_content.senddate</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.sql.Timestamp> SENDDATE = createField("senddate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_content.subject</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_content.replyTo</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.Integer> REPLYTO = createField("replyTo", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>fdtsucker.pvt_content.deleted</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.Integer> DELETED = createField("deleted", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>fdtsucker.pvt_content</code> table reference
	 */
	public PvtContent() {
		this("pvt_content", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.pvt_content</code> table reference
	 */
	public PvtContent(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT);
	}

	private PvtContent(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> aliased) {
		this(alias, aliased, null);
	}

	private PvtContent(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.Integer> getIdentity() {
		return com.forumdeitroll.persistence.jooq.Keys.IDENTITY_PVT_CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_PVT_CONTENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_PVT_CONTENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.PvtContent as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.PvtContent(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.PvtContent rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.PvtContent(name, null);
	}
}
