/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PvtRecipient extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord> {

	private static final long serialVersionUID = -1851456805;

	/**
	 * The singleton instance of <code>fdtsucker.pvt_recipient</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PvtRecipient PVT_RECIPIENT = new com.forumdeitroll.persistence.jooq.tables.PvtRecipient();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord.class;
	}

	/**
	 * The column <code>fdtsucker.pvt_recipient.pvt_id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord, java.lang.Integer> PVT_ID = createField("pvt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_recipient.recipient</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord, java.lang.String> RECIPIENT = createField("recipient", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.pvt_recipient.read</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord, java.lang.Integer> READ = createField("read", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>fdtsucker.pvt_recipient.deleted</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord, java.lang.Integer> DELETED = createField("deleted", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>fdtsucker.pvt_recipient</code> table reference
	 */
	public PvtRecipient() {
		this("pvt_recipient", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.pvt_recipient</code> table reference
	 */
	public PvtRecipient(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.PvtRecipient.PVT_RECIPIENT);
	}

	private PvtRecipient(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord> aliased) {
		this(alias, aliased, null);
	}

	private PvtRecipient(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.PvtRecipientRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.PvtRecipient as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.PvtRecipient(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.PvtRecipient rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.PvtRecipient(name, null);
	}
}
