/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quotes extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> {

	private static final long serialVersionUID = 1837401804;

	/**
	 * The singleton instance of <code>fdtsucker.quotes</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Quotes QUOTES = new com.forumdeitroll.persistence.jooq.tables.Quotes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord.class;
	}

	/**
	 * The column <code>fdtsucker.quotes.id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.quotes.nick</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord, java.lang.String> NICK = createField("nick", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.quotes.content</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.quotes</code> table reference
	 */
	public Quotes() {
		this("quotes", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.quotes</code> table reference
	 */
	public Quotes(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES);
	}

	private Quotes(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Quotes(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord, java.lang.Integer> getIdentity() {
		return com.forumdeitroll.persistence.jooq.Keys.IDENTITY_QUOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_QUOTES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_QUOTES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Quotes as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Quotes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Quotes rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Quotes(name, null);
	}
}
