/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sysinfo extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord> {

	private static final long serialVersionUID = 2057765323;

	/**
	 * The singleton instance of <code>fdtsucker.sysinfo</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Sysinfo SYSINFO = new com.forumdeitroll.persistence.jooq.tables.Sysinfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord.class;
	}

	/**
	 * The column <code>fdtsucker.sysinfo.key</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord, java.lang.String> KEY = createField("key", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.sysinfo.value</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord, java.lang.String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.sysinfo</code> table reference
	 */
	public Sysinfo() {
		this("sysinfo", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.sysinfo</code> table reference
	 */
	public Sysinfo(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Sysinfo.SYSINFO);
	}

	private Sysinfo(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sysinfo(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.SysinfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Sysinfo as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Sysinfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Sysinfo rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Sysinfo(name, null);
	}
}
