/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tags extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> {

	private static final long serialVersionUID = -779513276;

	/**
	 * The singleton instance of <code>fdtsucker.tags</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Tags TAGS = new com.forumdeitroll.persistence.jooq.tables.Tags();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.TagsRecord.class;
	}

	/**
	 * The column <code>fdtsucker.tags.tagName</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord, java.lang.String> TAGNAME = createField("tagName", org.jooq.impl.SQLDataType.VARCHAR.length(12).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.tags.used</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord, java.lang.Integer> USED = createField("used", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.tags</code> table reference
	 */
	public Tags() {
		this("tags", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.tags</code> table reference
	 */
	public Tags(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Tags.TAGS);
	}

	private Tags(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tags(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_TAGS_TAGNAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Tags as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Tags(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Tags rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Tags(name, null);
	}
}
