/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsBind extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> {

	private static final long serialVersionUID = -817854302;

	/**
	 * The singleton instance of <code>fdtsucker.tags_bind</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.TagsBind TAGS_BIND = new com.forumdeitroll.persistence.jooq.tables.TagsBind();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord.class;
	}

	/**
	 * The column <code>fdtsucker.tags_bind.t_id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord, java.lang.Integer> T_ID = createField("t_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.tags_bind.m_id</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord, java.lang.Integer> M_ID = createField("m_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.tags_bind.author</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB.length(255).nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.tags_bind</code> table reference
	 */
	public TagsBind() {
		this("tags_bind", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.tags_bind</code> table reference
	 */
	public TagsBind(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND);
	}

	private TagsBind(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> aliased) {
		this(alias, aliased, null);
	}

	private TagsBind(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> getPrimaryKey() {
		return com.forumdeitroll.persistence.jooq.Keys.KEY_TAGS_BIND_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord>>asList(com.forumdeitroll.persistence.jooq.Keys.KEY_TAGS_BIND_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.TagsBind as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.TagsBind(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.TagsBind rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.TagsBind(name, null);
	}
}
