/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Threads extends org.jooq.impl.TableImpl<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord> {

	private static final long serialVersionUID = -792066451;

	/**
	 * The singleton instance of <code>fdtsucker.threads</code>
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Threads THREADS = new com.forumdeitroll.persistence.jooq.tables.Threads();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord> getRecordType() {
		return com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord.class;
	}

	/**
	 * The column <code>fdtsucker.threads.threadId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord, java.lang.Integer> THREADID = createField("threadId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>fdtsucker.threads.lastId</code>.
	 */
	public final org.jooq.TableField<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord, java.lang.Integer> LASTID = createField("lastId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>fdtsucker.threads</code> table reference
	 */
	public Threads() {
		this("threads", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.threads</code> table reference
	 */
	public Threads(java.lang.String alias) {
		this(alias, com.forumdeitroll.persistence.jooq.tables.Threads.THREADS);
	}

	private Threads(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Threads(java.lang.String alias, org.jooq.Table<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.forumdeitroll.persistence.jooq.Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.forumdeitroll.persistence.jooq.tables.Threads as(java.lang.String alias) {
		return new com.forumdeitroll.persistence.jooq.tables.Threads(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.forumdeitroll.persistence.jooq.tables.Threads rename(java.lang.String name) {
		return new com.forumdeitroll.persistence.jooq.tables.Threads(name, null);
	}
}
