CREATE CACHED TABLE PUBLIC.AUTHORS(
    NICK TINYTEXT NOT NULL,
    MESSAGES INT NOT NULL,
    AVATAR MEDIUMBLOB,
    PASSWORD TINYTEXT NOT NULL,
    SALT TINYTEXT,
    HASH TINYTEXT,
    SIGNATURE_IMAGE MEDIUMBLOB
);

CREATE CACHED TABLE PUBLIC.MESSAGES(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEXT MEDIUMTEXT NOT NULL,
    DATE DATETIME NOT NULL,
    SUBJECT TINYTEXT NOT NULL,
    THREADID INT NOT NULL,
    PARENTID INT NOT NULL,
    AUTHOR VARCHAR(256) DEFAULT NULL,
    FORUM VARCHAR(256) DEFAULT NULL,
    VISIBLE BOOLEAN DEFAULT '1' NOT NULL,
    RANK INT NOT NULL DEFAULT '0'
);

CREATE CACHED TABLE PUBLIC.POLL(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(256) NOT NULL,
    TEXT MEDIUMTEXT NOT NULL,
    AUTHOR VARCHAR(256) NOT NULL,
    CREATIONDATE DATETIME NOT NULL,
    UPDATEDATE DATETIME NOT NULL
);

CREATE CACHED TABLE PUBLIC.POLL_QUESTION(
    POLLID INT NOT NULL,
    SEQUENCE INT NOT NULL,
    TEXT VARCHAR(256) NOT NULL,
    VOTES INT NOT NULL
);

CREATE CACHED TABLE PUBLIC.POLL_USER(
    NICK VARCHAR(256) NOT NULL,
    POLLID INT NOT NULL
);

CREATE CACHED TABLE PUBLIC.PREFERENCES(
    NICK TINYTEXT NOT NULL,
    KEY TINYTEXT NOT NULL,
    VALUE TINYTEXT NOT NULL
);

CREATE CACHED TABLE PUBLIC.PVT_CONTENT(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SENDER TEXT NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    SENDDATE DATETIME NOT NULL,
    SUBJECT TEXT NOT NULL,
    REPLYTO INT,
    DELETED INT DEFAULT 0
);

CREATE CACHED TABLE PUBLIC.PVT_RECIPIENT(
    PVT_ID INT NOT NULL,
    RECIPIENT TEXT NOT NULL,
    READ INT DEFAULT 0,
    DELETED INT DEFAULT 0
);

CREATE CACHED TABLE PUBLIC.QUOTES(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NICK TEXT NOT NULL,
    CONTENT TEXT NOT NULL
);

CREATE CACHED TABLE PUBLIC.SYSINFO(
    KEY TINYTEXT NOT NULL,
    VALUE TINYTEXT NOT NULL
);

CREATE CACHED TABLE PUBLIC.NOTIFICATION(
	ID INT DEFAULT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FROMNICK VARCHAR(256) NOT NULL,
	TONICK VARCHAR(256) NOT NULL,
	MSGID INT NOT NULL
);

CREATE CACHED TABLE PUBLIC.LIKES (
  NICK TINYTEXT NOT NULL,
  MSGID INT NOT NULL,
  VOTE BOOLEAN NULL NULL
);

CREATE INDEX ID_IDX ON MESSAGES(ID);

CREATE INDEX PARENTID_IDX ON MESSAGES(PARENTID);

CREATE INDEX THREADID_IDX ON MESSAGES(THREADID);

CREATE INDEX AUTHOR_IDX ON MESSAGES(AUTHOR);


-- native fulltedt search
CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";

CALL FT_INIT();

CALL FT_CREATE_INDEX('PUBLIC', 'MESSAGES', 'TEXT');

