/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdsRecord extends org.jooq.impl.UpdatableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 585011025;

	/**
	 * Setter for <code>fdtsucker.ads.id</code>.
	 */
	public AdsRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.ads.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.ads.title</code>.
	 */
	public AdsRecord setTitle(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.ads.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.ads.visurl</code>.
	 */
	public AdsRecord setVisurl(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.ads.visurl</code>.
	 */
	public java.lang.String getVisurl() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.ads.content</code>.
	 */
	public AdsRecord setContent(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.ads.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Ads.ADS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Ads.ADS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Ads.ADS.VISURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.forumdeitroll.persistence.jooq.tables.Ads.ADS.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getVisurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsRecord value3(java.lang.String value) {
		setVisurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsRecord value4(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AdsRecord
	 */
	public AdsRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Ads.ADS);
	}

	/**
	 * Create a detached, initialised AdsRecord
	 */
	public AdsRecord(java.lang.Integer id, java.lang.String title, java.lang.String visurl, java.lang.String content) {
		super(com.forumdeitroll.persistence.jooq.tables.Ads.ADS);

		setValue(0, id);
		setValue(1, title);
		setValue(2, visurl);
		setValue(3, content);
	}
}
