/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorsRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.AuthorsRecord> implements org.jooq.Record7<java.lang.String, java.lang.Integer, byte[], java.lang.String, java.lang.String, java.lang.String, byte[]> {

	private static final long serialVersionUID = 245224162;

	/**
	 * Setter for <code>fdtsucker.authors.nick</code>.
	 */
	public AuthorsRecord setNick(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.nick</code>.
	 */
	public java.lang.String getNick() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.authors.messages</code>.
	 */
	public AuthorsRecord setMessages(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.messages</code>.
	 */
	public java.lang.Integer getMessages() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.authors.avatar</code>.
	 */
	public AuthorsRecord setAvatar(byte[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.avatar</code>.
	 */
	public byte[] getAvatar() {
		return (byte[]) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.authors.password</code>.
	 */
	public AuthorsRecord setPassword(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.authors.salt</code>.
	 */
	public AuthorsRecord setSalt(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.salt</code>.
	 */
	public java.lang.String getSalt() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.authors.hash</code>.
	 */
	public AuthorsRecord setHash(java.lang.String value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.hash</code>.
	 */
	public java.lang.String getHash() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.authors.signature_image</code>.
	 */
	public AuthorsRecord setSignatureImage(byte[] value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.authors.signature_image</code>.
	 */
	public byte[] getSignatureImage() {
		return (byte[]) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.Integer, byte[], java.lang.String, java.lang.String, java.lang.String, byte[]> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.Integer, byte[], java.lang.String, java.lang.String, java.lang.String, byte[]> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.MESSAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.AVATAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.SALT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.HASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field7() {
		return com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS.SIGNATURE_IMAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMessages();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getAvatar();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSalt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getHash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value7() {
		return getSignatureImage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value1(java.lang.String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value2(java.lang.Integer value) {
		setMessages(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value3(byte[] value) {
		setAvatar(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value4(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value5(java.lang.String value) {
		setSalt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value6(java.lang.String value) {
		setHash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord value7(byte[] value) {
		setSignatureImage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorsRecord values(java.lang.String value1, java.lang.Integer value2, byte[] value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, byte[] value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AuthorsRecord
	 */
	public AuthorsRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS);
	}

	/**
	 * Create a detached, initialised AuthorsRecord
	 */
	public AuthorsRecord(java.lang.String nick, java.lang.Integer messages, byte[] avatar, java.lang.String password, java.lang.String salt, java.lang.String hash, byte[] signatureImage) {
		super(com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS);

		setValue(0, nick);
		setValue(1, messages);
		setValue(2, avatar);
		setValue(3, password);
		setValue(4, salt);
		setValue(5, hash);
		setValue(6, signatureImage);
	}
}
