/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarksRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.BookmarksRecord> implements org.jooq.Record3<java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1970930789;

	/**
	 * Setter for <code>fdtsucker.bookmarks.nick</code>.
	 */
	public BookmarksRecord setNick(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.bookmarks.nick</code>.
	 */
	public java.lang.String getNick() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.bookmarks.msgId</code>.
	 */
	public BookmarksRecord setMsgid(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.bookmarks.msgId</code>.
	 */
	public java.lang.Integer getMsgid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.bookmarks.subject</code>.
	 */
	public BookmarksRecord setSubject(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.bookmarks.subject</code>.
	 */
	public java.lang.String getSubject() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS.MSGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMsgid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarksRecord value1(java.lang.String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarksRecord value2(java.lang.Integer value) {
		setMsgid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarksRecord value3(java.lang.String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarksRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BookmarksRecord
	 */
	public BookmarksRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS);
	}

	/**
	 * Create a detached, initialised BookmarksRecord
	 */
	public BookmarksRecord(java.lang.String nick, java.lang.Integer msgid, java.lang.String subject) {
		super(com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS);

		setValue(0, nick);
		setValue(1, msgid);
		setValue(2, subject);
	}
}
