/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DigestRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.DigestRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -1604195237;

	/**
	 * Setter for <code>fdtsucker.digest.threadId</code>.
	 */
	public DigestRecord setThreadid(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.threadId</code>.
	 */
	public java.lang.Integer getThreadid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.digest.author</code>.
	 */
	public DigestRecord setAuthor(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.author</code>.
	 */
	public java.lang.String getAuthor() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.digest.subject</code>.
	 */
	public DigestRecord setSubject(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.subject</code>.
	 */
	public java.lang.String getSubject() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.digest.opener_text</code>.
	 */
	public DigestRecord setOpenerText(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.opener_text</code>.
	 */
	public java.lang.String getOpenerText() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.digest.excerpt</code>.
	 */
	public DigestRecord setExcerpt(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.excerpt</code>.
	 */
	public java.lang.String getExcerpt() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.digest.nrOfMessages</code>.
	 */
	public DigestRecord setNrofmessages(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.nrOfMessages</code>.
	 */
	public java.lang.Integer getNrofmessages() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.digest.startDate</code>.
	 */
	public DigestRecord setStartdate(java.sql.Timestamp value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.startDate</code>.
	 */
	public java.sql.Timestamp getStartdate() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>fdtsucker.digest.lastDate</code>.
	 */
	public DigestRecord setLastdate(java.sql.Timestamp value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.lastDate</code>.
	 */
	public java.sql.Timestamp getLastdate() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.THREADID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.OPENER_TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.EXCERPT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.NROFMESSAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.STARTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST.LASTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getThreadid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getOpenerText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getExcerpt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getNrofmessages();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getStartdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getLastdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value1(java.lang.Integer value) {
		setThreadid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value2(java.lang.String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value3(java.lang.String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value4(java.lang.String value) {
		setOpenerText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value5(java.lang.String value) {
		setExcerpt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value6(java.lang.Integer value) {
		setNrofmessages(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value7(java.sql.Timestamp value) {
		setStartdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value8(java.sql.Timestamp value) {
		setLastdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.sql.Timestamp value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DigestRecord
	 */
	public DigestRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST);
	}

	/**
	 * Create a detached, initialised DigestRecord
	 */
	public DigestRecord(java.lang.Integer threadid, java.lang.String author, java.lang.String subject, java.lang.String openerText, java.lang.String excerpt, java.lang.Integer nrofmessages, java.sql.Timestamp startdate, java.sql.Timestamp lastdate) {
		super(com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST);

		setValue(0, threadid);
		setValue(1, author);
		setValue(2, subject);
		setValue(3, openerText);
		setValue(4, excerpt);
		setValue(5, nrofmessages);
		setValue(6, startdate);
		setValue(7, lastdate);
	}
}
