/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.Digest;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DigestRecord extends TableRecordImpl<DigestRecord> implements Record8<Integer, String, String, String, String, Integer, Timestamp, Timestamp> {

	private static final long serialVersionUID = 458046880;

	/**
	 * Setter for <code>fdtsucker.digest.threadId</code>.
	 */
	public DigestRecord setThreadid(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.threadId</code>.
	 */
	public Integer getThreadid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.digest.author</code>.
	 */
	public DigestRecord setAuthor(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.author</code>.
	 */
	public String getAuthor() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.digest.subject</code>.
	 */
	public DigestRecord setSubject(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.subject</code>.
	 */
	public String getSubject() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.digest.opener_text</code>.
	 */
	public DigestRecord setOpenerText(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.opener_text</code>.
	 */
	public String getOpenerText() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.digest.excerpt</code>.
	 */
	public DigestRecord setExcerpt(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.excerpt</code>.
	 */
	public String getExcerpt() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.digest.nrOfMessages</code>.
	 */
	public DigestRecord setNrofmessages(Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.nrOfMessages</code>.
	 */
	public Integer getNrofmessages() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.digest.startDate</code>.
	 */
	public DigestRecord setStartdate(Timestamp value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.startDate</code>.
	 */
	public Timestamp getStartdate() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>fdtsucker.digest.lastDate</code>.
	 */
	public DigestRecord setLastdate(Timestamp value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.digest.lastDate</code>.
	 */
	public Timestamp getLastdate() {
		return (Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, String, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, String, String, String, Integer, Timestamp, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Digest.DIGEST.THREADID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Digest.DIGEST.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Digest.DIGEST.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Digest.DIGEST.OPENER_TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Digest.DIGEST.EXCERPT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Digest.DIGEST.NROFMESSAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Digest.DIGEST.STARTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return Digest.DIGEST.LASTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getThreadid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getOpenerText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getExcerpt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getNrofmessages();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getStartdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getLastdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value1(Integer value) {
		setThreadid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value2(String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value3(String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value4(String value) {
		setOpenerText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value5(String value) {
		setExcerpt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value6(Integer value) {
		setNrofmessages(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value7(Timestamp value) {
		setStartdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord value8(Timestamp value) {
		setLastdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Timestamp value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DigestRecord
	 */
	public DigestRecord() {
		super(Digest.DIGEST);
	}

	/**
	 * Create a detached, initialised DigestRecord
	 */
	public DigestRecord(Integer threadid, String author, String subject, String openerText, String excerpt, Integer nrofmessages, Timestamp startdate, Timestamp lastdate) {
		super(Digest.DIGEST);

		setValue(0, threadid);
		setValue(1, author);
		setValue(2, subject);
		setValue(3, openerText);
		setValue(4, excerpt);
		setValue(5, nrofmessages);
		setValue(6, startdate);
		setValue(7, lastdate);
	}
}
