/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LikesRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.LikesRecord> implements org.jooq.Record3<java.lang.String, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = -1266867099;

	/**
	 * Setter for <code>fdtsucker.likes.nick</code>.
	 */
	public LikesRecord setNick(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.likes.nick</code>.
	 */
	public java.lang.String getNick() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.likes.msgId</code>.
	 */
	public LikesRecord setMsgid(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.likes.msgId</code>.
	 */
	public java.lang.Integer getMsgid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.likes.vote</code>.
	 */
	public LikesRecord setVote(java.lang.Byte value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.likes.vote</code>.
	 */
	public java.lang.Byte getVote() {
		return (java.lang.Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Likes.LIKES.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Likes.LIKES.MSGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Likes.LIKES.VOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMsgid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getVote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord value1(java.lang.String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord value2(java.lang.Integer value) {
		setMsgid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord value3(java.lang.Byte value) {
		setVote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.Byte value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LikesRecord
	 */
	public LikesRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Likes.LIKES);
	}

	/**
	 * Create a detached, initialised LikesRecord
	 */
	public LikesRecord(java.lang.String nick, java.lang.Integer msgid, java.lang.Byte vote) {
		super(com.forumdeitroll.persistence.jooq.tables.Likes.LIKES);

		setValue(0, nick);
		setValue(1, msgid);
		setValue(2, vote);
	}
}
