/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.Messages;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends UpdatableRecordImpl<MessagesRecord> implements Record11<Integer, String, Timestamp, String, Integer, Integer, String, String, Byte, Integer, String> {

	private static final long serialVersionUID = -128558935;

	/**
	 * Setter for <code>fdtsucker.messages.id</code>.
	 */
	public MessagesRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.messages.text</code>.
	 */
	public MessagesRecord setText(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.text</code>.
	 */
	public String getText() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.messages.date</code>.
	 */
	public MessagesRecord setDate(Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.date</code>.
	 */
	public Timestamp getDate() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.messages.subject</code>.
	 */
	public MessagesRecord setSubject(String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.subject</code>.
	 */
	public String getSubject() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.messages.threadId</code>.
	 */
	public MessagesRecord setThreadid(Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.threadId</code>.
	 */
	public Integer getThreadid() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.messages.parentId</code>.
	 */
	public MessagesRecord setParentid(Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.parentId</code>.
	 */
	public Integer getParentid() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.messages.author</code>.
	 */
	public MessagesRecord setAuthor(String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.author</code>.
	 */
	public String getAuthor() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>fdtsucker.messages.forum</code>.
	 */
	public MessagesRecord setForum(String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.forum</code>.
	 */
	public String getForum() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>fdtsucker.messages.visible</code>.
	 */
	public MessagesRecord setVisible(Byte value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.visible</code>.
	 */
	public Byte getVisible() {
		return (Byte) getValue(8);
	}

	/**
	 * Setter for <code>fdtsucker.messages.rank</code>.
	 */
	public MessagesRecord setRank(Integer value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.rank</code>.
	 */
	public Integer getRank() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>fdtsucker.messages.fakeAuthor</code>.
	 */
	public MessagesRecord setFakeauthor(String value) {
		setValue(10, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.fakeAuthor</code>.
	 */
	public String getFakeauthor() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, Timestamp, String, Integer, Integer, String, String, Byte, Integer, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, Timestamp, String, Integer, Integer, String, String, Byte, Integer, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Messages.MESSAGES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Messages.MESSAGES.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Messages.MESSAGES.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Messages.MESSAGES.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Messages.MESSAGES.THREADID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Messages.MESSAGES.PARENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Messages.MESSAGES.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Messages.MESSAGES.FORUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field9() {
		return Messages.MESSAGES.VISIBLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Messages.MESSAGES.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Messages.MESSAGES.FAKEAUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getThreadid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getParentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getForum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value9() {
		return getVisible();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getFakeauthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value2(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value3(Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value4(String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value5(Integer value) {
		setThreadid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value6(Integer value) {
		setParentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value7(String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value8(String value) {
		setForum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value9(Byte value) {
		setVisible(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value10(Integer value) {
		setRank(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value11(String value) {
		setFakeauthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord values(Integer value1, String value2, Timestamp value3, String value4, Integer value5, Integer value6, String value7, String value8, Byte value9, Integer value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessagesRecord
	 */
	public MessagesRecord() {
		super(Messages.MESSAGES);
	}

	/**
	 * Create a detached, initialised MessagesRecord
	 */
	public MessagesRecord(Integer id, String text, Timestamp date, String subject, Integer threadid, Integer parentid, String author, String forum, Byte visible, Integer rank, String fakeauthor) {
		super(Messages.MESSAGES);

		setValue(0, id);
		setValue(1, text);
		setValue(2, date);
		setValue(3, subject);
		setValue(4, threadid);
		setValue(5, parentid);
		setValue(6, author);
		setValue(7, forum);
		setValue(8, visible);
		setValue(9, rank);
		setValue(10, fakeauthor);
	}
}
