/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends org.jooq.impl.UpdatableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> {

	private static final long serialVersionUID = 1355955796;

	/**
	 * Setter for <code>fdtsucker.messages.id</code>.
	 */
	public MessagesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.messages.text</code>.
	 */
	public MessagesRecord setText(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.messages.date</code>.
	 */
	public MessagesRecord setDate(java.sql.Timestamp value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.messages.subject</code>.
	 */
	public MessagesRecord setSubject(java.lang.String value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.subject</code>.
	 */
	public java.lang.String getSubject() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.messages.threadId</code>.
	 */
	public MessagesRecord setThreadid(java.lang.Integer value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.threadId</code>.
	 */
	public java.lang.Integer getThreadid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.messages.parentId</code>.
	 */
	public MessagesRecord setParentid(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.parentId</code>.
	 */
	public java.lang.Integer getParentid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.messages.author</code>.
	 */
	public MessagesRecord setAuthor(java.lang.String value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.author</code>.
	 */
	public java.lang.String getAuthor() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>fdtsucker.messages.forum</code>.
	 */
	public MessagesRecord setForum(java.lang.String value) {
		setValue(7, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.forum</code>.
	 */
	public java.lang.String getForum() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>fdtsucker.messages.visible</code>.
	 */
	public MessagesRecord setVisible(java.lang.Byte value) {
		setValue(8, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.visible</code>.
	 */
	public java.lang.Byte getVisible() {
		return (java.lang.Byte) getValue(8);
	}

	/**
	 * Setter for <code>fdtsucker.messages.rank</code>.
	 */
	public MessagesRecord setRank(java.lang.Integer value) {
		setValue(9, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.messages.rank</code>.
	 */
	public java.lang.Integer getRank() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.THREADID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.PARENTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.FORUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field9() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.VISIBLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getThreadid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getParentid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getForum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value9() {
		return getVisible();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value2(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value3(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value4(java.lang.String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value5(java.lang.Integer value) {
		setThreadid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value6(java.lang.Integer value) {
		setParentid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value7(java.lang.String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value8(java.lang.String value) {
		setForum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value9(java.lang.Byte value) {
		setVisible(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value10(java.lang.Integer value) {
		setRank(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord values(java.lang.Integer value1, java.lang.String value2, java.sql.Timestamp value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.lang.Byte value9, java.lang.Integer value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessagesRecord
	 */
	public MessagesRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES);
	}

	/**
	 * Create a detached, initialised MessagesRecord
	 */
	public MessagesRecord(java.lang.Integer id, java.lang.String text, java.sql.Timestamp date, java.lang.String subject, java.lang.Integer threadid, java.lang.Integer parentid, java.lang.String author, java.lang.String forum, java.lang.Byte visible, java.lang.Integer rank) {
		super(com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES);

		setValue(0, id);
		setValue(1, text);
		setValue(2, date);
		setValue(3, subject);
		setValue(4, threadid);
		setValue(5, parentid);
		setValue(6, author);
		setValue(7, forum);
		setValue(8, visible);
		setValue(9, rank);
	}
}
