/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.PollQuestion;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollQuestionRecord extends TableRecordImpl<PollQuestionRecord> implements Record4<Integer, Integer, String, Integer> {

	private static final long serialVersionUID = -1524940483;

	/**
	 * Setter for <code>fdtsucker.poll_question.pollId</code>.
	 */
	public PollQuestionRecord setPollid(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_question.pollId</code>.
	 */
	public Integer getPollid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.poll_question.sequence</code>.
	 */
	public PollQuestionRecord setSequence(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_question.sequence</code>.
	 */
	public Integer getSequence() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.poll_question.text</code>.
	 */
	public PollQuestionRecord setText(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_question.text</code>.
	 */
	public String getText() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.poll_question.votes</code>.
	 */
	public PollQuestionRecord setVotes(Integer value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_question.votes</code>.
	 */
	public Integer getVotes() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PollQuestion.POLL_QUESTION.POLLID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return PollQuestion.POLL_QUESTION.SEQUENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PollQuestion.POLL_QUESTION.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return PollQuestion.POLL_QUESTION.VOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPollid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSequence();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getVotes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollQuestionRecord value1(Integer value) {
		setPollid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollQuestionRecord value2(Integer value) {
		setSequence(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollQuestionRecord value3(String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollQuestionRecord value4(Integer value) {
		setVotes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollQuestionRecord values(Integer value1, Integer value2, String value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PollQuestionRecord
	 */
	public PollQuestionRecord() {
		super(PollQuestion.POLL_QUESTION);
	}

	/**
	 * Create a detached, initialised PollQuestionRecord
	 */
	public PollQuestionRecord(Integer pollid, Integer sequence, String text, Integer votes) {
		super(PollQuestion.POLL_QUESTION);

		setValue(0, pollid);
		setValue(1, sequence);
		setValue(2, text);
		setValue(3, votes);
	}
}
