/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.PollUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollUserRecord extends TableRecordImpl<PollUserRecord> implements Record2<String, Integer> {

	private static final long serialVersionUID = -168894014;

	/**
	 * Setter for <code>fdtsucker.poll_user.nick</code>.
	 */
	public PollUserRecord setNick(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_user.nick</code>.
	 */
	public String getNick() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.poll_user.pollId</code>.
	 */
	public PollUserRecord setPollid(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_user.pollId</code>.
	 */
	public Integer getPollid() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return PollUser.POLL_USER.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return PollUser.POLL_USER.POLLID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPollid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUserRecord value1(String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUserRecord value2(Integer value) {
		setPollid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUserRecord values(String value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PollUserRecord
	 */
	public PollUserRecord() {
		super(PollUser.POLL_USER);
	}

	/**
	 * Create a detached, initialised PollUserRecord
	 */
	public PollUserRecord(String nick, Integer pollid) {
		super(PollUser.POLL_USER);

		setValue(0, nick);
		setValue(1, pollid);
	}
}
