/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollUserRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.PollUserRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 539908005;

	/**
	 * Setter for <code>fdtsucker.poll_user.nick</code>.
	 */
	public PollUserRecord setNick(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_user.nick</code>.
	 */
	public java.lang.String getNick() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.poll_user.pollId</code>.
	 */
	public PollUserRecord setPollid(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.poll_user.pollId</code>.
	 */
	public java.lang.Integer getPollid() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.forumdeitroll.persistence.jooq.tables.PollUser.POLL_USER.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.PollUser.POLL_USER.POLLID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPollid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUserRecord value1(java.lang.String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUserRecord value2(java.lang.Integer value) {
		setPollid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUserRecord values(java.lang.String value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PollUserRecord
	 */
	public PollUserRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.PollUser.POLL_USER);
	}

	/**
	 * Create a detached, initialised PollUserRecord
	 */
	public PollUserRecord(java.lang.String nick, java.lang.Integer pollid) {
		super(com.forumdeitroll.persistence.jooq.tables.PollUser.POLL_USER);

		setValue(0, nick);
		setValue(1, pollid);
	}
}
