/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PreferencesRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.PreferencesRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1158071965;

	/**
	 * Setter for <code>fdtsucker.preferences.nick</code>.
	 */
	public PreferencesRecord setNick(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.preferences.nick</code>.
	 */
	public java.lang.String getNick() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.preferences.key</code>.
	 */
	public PreferencesRecord setKey(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.preferences.key</code>.
	 */
	public java.lang.String getKey() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.preferences.value</code>.
	 */
	public PreferencesRecord setValue(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.preferences.value</code>.
	 */
	public java.lang.String getValue() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PreferencesRecord value1(java.lang.String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PreferencesRecord value2(java.lang.String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PreferencesRecord value3(java.lang.String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PreferencesRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PreferencesRecord
	 */
	public PreferencesRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES);
	}

	/**
	 * Create a detached, initialised PreferencesRecord
	 */
	public PreferencesRecord(java.lang.String nick, java.lang.String key, java.lang.String value) {
		super(com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES);

		setValue(0, nick);
		setValue(1, key);
		setValue(2, value);
	}
}
