/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PvtContentRecord extends org.jooq.impl.UpdatableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 136818336;

	/**
	 * Setter for <code>fdtsucker.pvt_content.id</code>.
	 */
	public PvtContentRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.sender</code>.
	 */
	public PvtContentRecord setSender(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.sender</code>.
	 */
	public java.lang.String getSender() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.content</code>.
	 */
	public PvtContentRecord setContent(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.senddate</code>.
	 */
	public PvtContentRecord setSenddate(java.sql.Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.senddate</code>.
	 */
	public java.sql.Timestamp getSenddate() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.subject</code>.
	 */
	public PvtContentRecord setSubject(java.lang.String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.subject</code>.
	 */
	public java.lang.String getSubject() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.replyTo</code>.
	 */
	public PvtContentRecord setReplyto(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.replyTo</code>.
	 */
	public java.lang.Integer getReplyto() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.deleted</code>.
	 */
	public PvtContentRecord setDeleted(java.lang.Integer value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.deleted</code>.
	 */
	public java.lang.Integer getDeleted() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.SENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.SENDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.REPLYTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getSenddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getReplyto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value2(java.lang.String value) {
		setSender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value3(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value4(java.sql.Timestamp value) {
		setSenddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value5(java.lang.String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value6(java.lang.Integer value) {
		setReplyto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value7(java.lang.Integer value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5, java.lang.Integer value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PvtContentRecord
	 */
	public PvtContentRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT);
	}

	/**
	 * Create a detached, initialised PvtContentRecord
	 */
	public PvtContentRecord(java.lang.Integer id, java.lang.String sender, java.lang.String content, java.sql.Timestamp senddate, java.lang.String subject, java.lang.Integer replyto, java.lang.Integer deleted) {
		super(com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT);

		setValue(0, id);
		setValue(1, sender);
		setValue(2, content);
		setValue(3, senddate);
		setValue(4, subject);
		setValue(5, replyto);
		setValue(6, deleted);
	}
}
