/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.PvtContent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PvtContentRecord extends UpdatableRecordImpl<PvtContentRecord> implements Record7<Integer, String, String, Timestamp, String, Integer, Integer> {

	private static final long serialVersionUID = -904050542;

	/**
	 * Setter for <code>fdtsucker.pvt_content.id</code>.
	 */
	public PvtContentRecord setId(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.sender</code>.
	 */
	public PvtContentRecord setSender(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.sender</code>.
	 */
	public String getSender() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.content</code>.
	 */
	public PvtContentRecord setContent(String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.content</code>.
	 */
	public String getContent() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.senddate</code>.
	 */
	public PvtContentRecord setSenddate(Timestamp value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.senddate</code>.
	 */
	public Timestamp getSenddate() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.subject</code>.
	 */
	public PvtContentRecord setSubject(String value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.subject</code>.
	 */
	public String getSubject() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.replyTo</code>.
	 */
	public PvtContentRecord setReplyto(Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.replyTo</code>.
	 */
	public Integer getReplyto() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>fdtsucker.pvt_content.deleted</code>.
	 */
	public PvtContentRecord setDeleted(Integer value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.pvt_content.deleted</code>.
	 */
	public Integer getDeleted() {
		return (Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, Timestamp, String, Integer, Integer> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, Timestamp, String, Integer, Integer> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PvtContent.PVT_CONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return PvtContent.PVT_CONTENT.SENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return PvtContent.PVT_CONTENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return PvtContent.PVT_CONTENT.SENDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return PvtContent.PVT_CONTENT.SUBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return PvtContent.PVT_CONTENT.REPLYTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return PvtContent.PVT_CONTENT.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getSenddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSubject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getReplyto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value2(String value) {
		setSender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value3(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value4(Timestamp value) {
		setSenddate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value5(String value) {
		setSubject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value6(Integer value) {
		setReplyto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord value7(Integer value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PvtContentRecord values(Integer value1, String value2, String value3, Timestamp value4, String value5, Integer value6, Integer value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PvtContentRecord
	 */
	public PvtContentRecord() {
		super(PvtContent.PVT_CONTENT);
	}

	/**
	 * Create a detached, initialised PvtContentRecord
	 */
	public PvtContentRecord(Integer id, String sender, String content, Timestamp senddate, String subject, Integer replyto, Integer deleted) {
		super(PvtContent.PVT_CONTENT);

		setValue(0, id);
		setValue(1, sender);
		setValue(2, content);
		setValue(3, senddate);
		setValue(4, subject);
		setValue(5, replyto);
		setValue(6, deleted);
	}
}
