/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuotesRecord extends org.jooq.impl.UpdatableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1509058810;

	/**
	 * Setter for <code>fdtsucker.quotes.id</code>.
	 */
	public QuotesRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.quotes.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.quotes.nick</code>.
	 */
	public QuotesRecord setNick(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.quotes.nick</code>.
	 */
	public java.lang.String getNick() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.quotes.content</code>.
	 */
	public QuotesRecord setContent(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.quotes.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuotesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuotesRecord value2(java.lang.String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuotesRecord value3(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuotesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QuotesRecord
	 */
	public QuotesRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES);
	}

	/**
	 * Create a detached, initialised QuotesRecord
	 */
	public QuotesRecord(java.lang.Integer id, java.lang.String nick, java.lang.String content) {
		super(com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES);

		setValue(0, id);
		setValue(1, nick);
		setValue(2, content);
	}
}
