/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1039819139;

	/**
	 * Setter for <code>fdtsucker.tags.tagName</code>.
	 */
	public TagsRecord setTagname(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.tags.tagName</code>.
	 */
	public java.lang.String getTagname() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.tags.used</code>.
	 */
	public TagsRecord setUsed(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.tags.used</code>.
	 */
	public java.lang.Integer getUsed() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Tags.TAGS.TAGNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Tags.TAGS.USED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getTagname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUsed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord value1(java.lang.String value) {
		setTagname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord value2(java.lang.Integer value) {
		setUsed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord values(java.lang.String value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TagsRecord
	 */
	public TagsRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Tags.TAGS);
	}

	/**
	 * Create a detached, initialised TagsRecord
	 */
	public TagsRecord(java.lang.String tagname, java.lang.Integer used) {
		super(com.forumdeitroll.persistence.jooq.tables.Tags.TAGS);

		setValue(0, tagname);
		setValue(1, used);
	}
}
