/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsBindRecord extends org.jooq.impl.UpdatableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -249771722;

	/**
	 * Setter for <code>fdtsucker.tags_bind.t_id</code>.
	 */
	public TagsBindRecord setTId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.tags_bind.t_id</code>.
	 */
	public java.lang.Integer getTId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.tags_bind.m_id</code>.
	 */
	public TagsBindRecord setMId(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.tags_bind.m_id</code>.
	 */
	public java.lang.Integer getMId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.tags_bind.author</code>.
	 */
	public TagsBindRecord setAuthor(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.tags_bind.author</code>.
	 */
	public java.lang.String getAuthor() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND.T_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND.M_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getMId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsBindRecord value1(java.lang.Integer value) {
		setTId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsBindRecord value2(java.lang.Integer value) {
		setMId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsBindRecord value3(java.lang.String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsBindRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TagsBindRecord
	 */
	public TagsBindRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND);
	}

	/**
	 * Create a detached, initialised TagsBindRecord
	 */
	public TagsBindRecord(java.lang.Integer tId, java.lang.Integer mId, java.lang.String author) {
		super(com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND);

		setValue(0, tId);
		setValue(1, mId);
		setValue(2, author);
	}
}
