/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThreadsRecord extends org.jooq.impl.TableRecordImpl<com.forumdeitroll.persistence.jooq.tables.records.ThreadsRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -777658334;

	/**
	 * Setter for <code>fdtsucker.threads.threadId</code>.
	 */
	public ThreadsRecord setThreadid(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.threads.threadId</code>.
	 */
	public java.lang.Integer getThreadid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.threads.lastId</code>.
	 */
	public ThreadsRecord setLastid(java.lang.Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.threads.lastId</code>.
	 */
	public java.lang.Integer getLastid() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.forumdeitroll.persistence.jooq.tables.Threads.THREADS.THREADID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.forumdeitroll.persistence.jooq.tables.Threads.THREADS.LASTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getThreadid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getLastid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThreadsRecord value1(java.lang.Integer value) {
		setThreadid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThreadsRecord value2(java.lang.Integer value) {
		setLastid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThreadsRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ThreadsRecord
	 */
	public ThreadsRecord() {
		super(com.forumdeitroll.persistence.jooq.tables.Threads.THREADS);
	}

	/**
	 * Create a detached, initialised ThreadsRecord
	 */
	public ThreadsRecord(java.lang.Integer threadid, java.lang.Integer lastid) {
		super(com.forumdeitroll.persistence.jooq.tables.Threads.THREADS);

		setValue(0, threadid);
		setValue(1, lastid);
	}
}
