/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.Threads;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThreadsRecord extends TableRecordImpl<ThreadsRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 1266123192;

	/**
	 * Setter for <code>fdtsucker.threads.threadId</code>.
	 */
	public ThreadsRecord setThreadid(Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.threads.threadId</code>.
	 */
	public Integer getThreadid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.threads.lastId</code>.
	 */
	public ThreadsRecord setLastid(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.threads.lastId</code>.
	 */
	public Integer getLastid() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Threads.THREADS.THREADID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Threads.THREADS.LASTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getThreadid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getLastid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThreadsRecord value1(Integer value) {
		setThreadid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThreadsRecord value2(Integer value) {
		setLastid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ThreadsRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ThreadsRecord
	 */
	public ThreadsRecord() {
		super(Threads.THREADS);
	}

	/**
	 * Create a detached, initialised ThreadsRecord
	 */
	public ThreadsRecord(Integer threadid, Integer lastid) {
		super(Threads.THREADS);

		setValue(0, threadid);
		setValue(1, lastid);
	}
}
