/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.DigestParticipantRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DigestParticipant extends TableImpl<DigestParticipantRecord> {

	private static final long serialVersionUID = -1717882944;

	/**
	 * The reference instance of <code>fdtsucker.digest_participant</code>
	 */
	public static final DigestParticipant DIGEST_PARTICIPANT = new DigestParticipant();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DigestParticipantRecord> getRecordType() {
		return DigestParticipantRecord.class;
	}

	/**
	 * The column <code>fdtsucker.digest_participant.threadId</code>.
	 */
	public final TableField<DigestParticipantRecord, Integer> THREADID = createField("threadId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>fdtsucker.digest_participant.author</code>.
	 */
	public final TableField<DigestParticipantRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>fdtsucker.digest_participant</code> table reference
	 */
	public DigestParticipant() {
		this("digest_participant", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.digest_participant</code> table reference
	 */
	public DigestParticipant(String alias) {
		this(alias, DIGEST_PARTICIPANT);
	}

	private DigestParticipant(String alias, Table<DigestParticipantRecord> aliased) {
		this(alias, aliased, null);
	}

	private DigestParticipant(String alias, Table<DigestParticipantRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DigestParticipant as(String alias) {
		return new DigestParticipant(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DigestParticipant rename(String name) {
		return new DigestParticipant(name, null);
	}
}
