/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.ForumsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Forums extends TableImpl<ForumsRecord> {

	private static final long serialVersionUID = -1296105452;

	/**
	 * The reference instance of <code>fdtsucker.forums</code>
	 */
	public static final Forums FORUMS = new Forums();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ForumsRecord> getRecordType() {
		return ForumsRecord.class;
	}

	/**
	 * The column <code>fdtsucker.forums.id</code>.
	 */
	public final TableField<ForumsRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * Create a <code>fdtsucker.forums</code> table reference
	 */
	public Forums() {
		this("forums", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.forums</code> table reference
	 */
	public Forums(String alias) {
		this(alias, FORUMS);
	}

	private Forums(String alias, Table<ForumsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Forums(String alias, Table<ForumsRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Forums as(String alias) {
		return new Forums(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Forums rename(String name) {
		return new Forums(name, null);
	}
}
