/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.tables.records.PollUserRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollUser extends TableImpl<PollUserRecord> {

	private static final long serialVersionUID = -1657724609;

	/**
	 * The reference instance of <code>fdtsucker.poll_user</code>
	 */
	public static final PollUser POLL_USER = new PollUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PollUserRecord> getRecordType() {
		return PollUserRecord.class;
	}

	/**
	 * The column <code>fdtsucker.poll_user.nick</code>.
	 */
	public final TableField<PollUserRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.poll_user.pollId</code>.
	 */
	public final TableField<PollUserRecord, Integer> POLLID = createField("pollId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.poll_user</code> table reference
	 */
	public PollUser() {
		this("poll_user", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.poll_user</code> table reference
	 */
	public PollUser(String alias) {
		this(alias, POLL_USER);
	}

	private PollUser(String alias, Table<PollUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private PollUser(String alias, Table<PollUserRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollUser as(String alias) {
		return new PollUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PollUser rename(String name) {
		return new PollUser(name, null);
	}
}
