/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables;


import com.forumdeitroll.persistence.jooq.Fdtsucker;
import com.forumdeitroll.persistence.jooq.Keys;
import com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quotes extends TableImpl<QuotesRecord> {

	private static final long serialVersionUID = -386043485;

	/**
	 * The reference instance of <code>fdtsucker.quotes</code>
	 */
	public static final Quotes QUOTES = new Quotes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<QuotesRecord> getRecordType() {
		return QuotesRecord.class;
	}

	/**
	 * The column <code>fdtsucker.quotes.id</code>.
	 */
	public final TableField<QuotesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.quotes.nick</code>.
	 */
	public final TableField<QuotesRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>fdtsucker.quotes.content</code>.
	 */
	public final TableField<QuotesRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>fdtsucker.quotes</code> table reference
	 */
	public Quotes() {
		this("quotes", null);
	}

	/**
	 * Create an aliased <code>fdtsucker.quotes</code> table reference
	 */
	public Quotes(String alias) {
		this(alias, QUOTES);
	}

	private Quotes(String alias, Table<QuotesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Quotes(String alias, Table<QuotesRecord> aliased, Field<?>[] parameters) {
		super(alias, Fdtsucker.FDTSUCKER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<QuotesRecord, Integer> getIdentity() {
		return Keys.IDENTITY_QUOTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<QuotesRecord> getPrimaryKey() {
		return Keys.KEY_QUOTES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<QuotesRecord>> getKeys() {
		return Arrays.<UniqueKey<QuotesRecord>>asList(Keys.KEY_QUOTES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Quotes as(String alias) {
		return new Quotes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Quotes rename(String name) {
		return new Quotes(name, null);
	}
}
