/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq;


import com.forumdeitroll.persistence.jooq.tables.*;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fdtsucker extends SchemaImpl {

	private static final long serialVersionUID = -227639616;

	/**
	 * The reference instance of <code>fdtsucker</code>
	 */
	public static final Fdtsucker FDTSUCKER = new Fdtsucker();

	/**
	 * No further instances allowed
	 */
	private Fdtsucker() {
		super("fdtsucker");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Ads.ADS,
			Authors.AUTHORS,
			Bookmarks.BOOKMARKS,
			Digest.DIGEST,
			DigestParticipant.DIGEST_PARTICIPANT,
			Likes.LIKES,
			Messages.MESSAGES,
			Notification.NOTIFICATION,
			Poll.POLL,
			PollQuestion.POLL_QUESTION,
			PollUser.POLL_USER,
			Preferences.PREFERENCES,
			PvtContent.PVT_CONTENT,
			PvtRecipient.PVT_RECIPIENT,
			Quotes.QUOTES,
			Sysinfo.SYSINFO,
			Tagnames.TAGNAMES,
			Tags.TAGS,
			TagsBind.TAGS_BIND,
			Threads.THREADS);
	}
}
