/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>fdtsucker</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.Integer> IDENTITY_ADS = Identities0.IDENTITY_ADS;
	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> IDENTITY_MESSAGES = Identities0.IDENTITY_MESSAGES;
	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.Integer> IDENTITY_NOTIFICATION = Identities0.IDENTITY_NOTIFICATION;
	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.Integer> IDENTITY_POLL = Identities0.IDENTITY_POLL;
	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.Integer> IDENTITY_PVT_CONTENT = Identities0.IDENTITY_PVT_CONTENT;
	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord, java.lang.Integer> IDENTITY_QUOTES = Identities0.IDENTITY_QUOTES;
	public static final org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.TagnamesRecord, java.lang.Integer> IDENTITY_TAGNAMES = Identities0.IDENTITY_TAGNAMES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> KEY_ADS_PRIMARY = UniqueKeys0.KEY_ADS_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> KEY_MESSAGES_PRIMARY = UniqueKeys0.KEY_MESSAGES_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> KEY_NOTIFICATION_PRIMARY = UniqueKeys0.KEY_NOTIFICATION_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> KEY_POLL_PRIMARY = UniqueKeys0.KEY_POLL_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> KEY_PVT_CONTENT_PRIMARY = UniqueKeys0.KEY_PVT_CONTENT_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> KEY_QUOTES_PRIMARY = UniqueKeys0.KEY_QUOTES_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagnamesRecord> KEY_TAGNAMES_PRIMARY = UniqueKeys0.KEY_TAGNAMES_PRIMARY;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> KEY_TAGS_TAGNAME = UniqueKeys0.KEY_TAGS_TAGNAME;
	public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> KEY_TAGS_BIND_PRIMARY = UniqueKeys0.KEY_TAGS_BIND_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord, java.lang.Integer> IDENTITY_ADS = createIdentity(com.forumdeitroll.persistence.jooq.tables.Ads.ADS, com.forumdeitroll.persistence.jooq.tables.Ads.ADS.ID);
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord, java.lang.Integer> IDENTITY_MESSAGES = createIdentity(com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES, com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.ID);
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord, java.lang.Integer> IDENTITY_NOTIFICATION = createIdentity(com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION, com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION.ID);
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.PollRecord, java.lang.Integer> IDENTITY_POLL = createIdentity(com.forumdeitroll.persistence.jooq.tables.Poll.POLL, com.forumdeitroll.persistence.jooq.tables.Poll.POLL.ID);
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord, java.lang.Integer> IDENTITY_PVT_CONTENT = createIdentity(com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT, com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.ID);
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord, java.lang.Integer> IDENTITY_QUOTES = createIdentity(com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES, com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES.ID);
		public static org.jooq.Identity<com.forumdeitroll.persistence.jooq.tables.records.TagnamesRecord, java.lang.Integer> IDENTITY_TAGNAMES = createIdentity(com.forumdeitroll.persistence.jooq.tables.Tagnames.TAGNAMES, com.forumdeitroll.persistence.jooq.tables.Tagnames.TAGNAMES.T_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.AdsRecord> KEY_ADS_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Ads.ADS, com.forumdeitroll.persistence.jooq.tables.Ads.ADS.ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.MessagesRecord> KEY_MESSAGES_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES, com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES.ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.NotificationRecord> KEY_NOTIFICATION_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION, com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION.ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PollRecord> KEY_POLL_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Poll.POLL, com.forumdeitroll.persistence.jooq.tables.Poll.POLL.ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.PvtContentRecord> KEY_PVT_CONTENT_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT, com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT.ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.QuotesRecord> KEY_QUOTES_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES, com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES.ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagnamesRecord> KEY_TAGNAMES_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Tagnames.TAGNAMES, com.forumdeitroll.persistence.jooq.tables.Tagnames.TAGNAMES.T_ID);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsRecord> KEY_TAGS_TAGNAME = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.Tags.TAGS, com.forumdeitroll.persistence.jooq.tables.Tags.TAGS.TAGNAME);
		public static final org.jooq.UniqueKey<com.forumdeitroll.persistence.jooq.tables.records.TagsBindRecord> KEY_TAGS_BIND_PRIMARY = createUniqueKey(com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND, com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND.T_ID, com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND.M_ID);
	}
}
