/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in fdtsucker
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table fdtsucker.ads
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Ads ADS = com.forumdeitroll.persistence.jooq.tables.Ads.ADS;

	/**
	 * The table fdtsucker.authors
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Authors AUTHORS = com.forumdeitroll.persistence.jooq.tables.Authors.AUTHORS;

	/**
	 * The table fdtsucker.bookmarks
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Bookmarks BOOKMARKS = com.forumdeitroll.persistence.jooq.tables.Bookmarks.BOOKMARKS;

	/**
	 * The table fdtsucker.digest
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Digest DIGEST = com.forumdeitroll.persistence.jooq.tables.Digest.DIGEST;

	/**
	 * The table fdtsucker.digest_participant
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.DigestParticipant DIGEST_PARTICIPANT = com.forumdeitroll.persistence.jooq.tables.DigestParticipant.DIGEST_PARTICIPANT;

	/**
	 * The table fdtsucker.likes
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Likes LIKES = com.forumdeitroll.persistence.jooq.tables.Likes.LIKES;

	/**
	 * The table fdtsucker.messages
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Messages MESSAGES = com.forumdeitroll.persistence.jooq.tables.Messages.MESSAGES;

	/**
	 * The table fdtsucker.notification
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Notification NOTIFICATION = com.forumdeitroll.persistence.jooq.tables.Notification.NOTIFICATION;

	/**
	 * The table fdtsucker.poll
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Poll POLL = com.forumdeitroll.persistence.jooq.tables.Poll.POLL;

	/**
	 * The table fdtsucker.poll_question
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PollQuestion POLL_QUESTION = com.forumdeitroll.persistence.jooq.tables.PollQuestion.POLL_QUESTION;

	/**
	 * The table fdtsucker.poll_user
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PollUser POLL_USER = com.forumdeitroll.persistence.jooq.tables.PollUser.POLL_USER;

	/**
	 * The table fdtsucker.preferences
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Preferences PREFERENCES = com.forumdeitroll.persistence.jooq.tables.Preferences.PREFERENCES;

	/**
	 * The table fdtsucker.pvt_content
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PvtContent PVT_CONTENT = com.forumdeitroll.persistence.jooq.tables.PvtContent.PVT_CONTENT;

	/**
	 * The table fdtsucker.pvt_recipient
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.PvtRecipient PVT_RECIPIENT = com.forumdeitroll.persistence.jooq.tables.PvtRecipient.PVT_RECIPIENT;

	/**
	 * The table fdtsucker.quotes
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Quotes QUOTES = com.forumdeitroll.persistence.jooq.tables.Quotes.QUOTES;

	/**
	 * The table fdtsucker.sysinfo
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Sysinfo SYSINFO = com.forumdeitroll.persistence.jooq.tables.Sysinfo.SYSINFO;

	/**
	 * The table fdtsucker.tagnames
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Tagnames TAGNAMES = com.forumdeitroll.persistence.jooq.tables.Tagnames.TAGNAMES;

	/**
	 * The table fdtsucker.tags
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Tags TAGS = com.forumdeitroll.persistence.jooq.tables.Tags.TAGS;

	/**
	 * The table fdtsucker.tags_bind
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.TagsBind TAGS_BIND = com.forumdeitroll.persistence.jooq.tables.TagsBind.TAGS_BIND;

	/**
	 * The table fdtsucker.threads
	 */
	public static final com.forumdeitroll.persistence.jooq.tables.Threads THREADS = com.forumdeitroll.persistence.jooq.tables.Threads.THREADS;
}
