/**
 * This class is generated by jOOQ
 */
package com.forumdeitroll.persistence.jooq.tables.records;


import com.forumdeitroll.persistence.jooq.tables.Likes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LikesRecord extends TableRecordImpl<LikesRecord> implements Record3<String, Integer, Byte> {

	private static final long serialVersionUID = 89900525;

	/**
	 * Setter for <code>fdtsucker.likes.nick</code>.
	 */
	public LikesRecord setNick(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.likes.nick</code>.
	 */
	public String getNick() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>fdtsucker.likes.msgId</code>.
	 */
	public LikesRecord setMsgid(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.likes.msgId</code>.
	 */
	public Integer getMsgid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>fdtsucker.likes.vote</code>.
	 */
	public LikesRecord setVote(Byte value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>fdtsucker.likes.vote</code>.
	 */
	public Byte getVote() {
		return (Byte) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, Byte> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, Byte> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Likes.LIKES.NICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Likes.LIKES.MSGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field3() {
		return Likes.LIKES.VOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getNick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getMsgid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value3() {
		return getVote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord value1(String value) {
		setNick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord value2(Integer value) {
		setMsgid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord value3(Byte value) {
		setVote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LikesRecord values(String value1, Integer value2, Byte value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LikesRecord
	 */
	public LikesRecord() {
		super(Likes.LIKES);
	}

	/**
	 * Create a detached, initialised LikesRecord
	 */
	public LikesRecord(String nick, Integer msgid, Byte vote) {
		super(Likes.LIKES);

		setValue(0, nick);
		setValue(1, msgid);
		setValue(2, vote);
	}
}
